language: java
jdk:
- oraclejdk7
- openjdk6
- openjdk7
env:
  global:
  - MAVEN_URL=http://apache.mirrors.pair.com/maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.tar.gz
  - secure: gLzfcqZtlmSKQTmWfZnkzKEWWtBb9U98Nu30BdFqp35KTqnUaO92eYoO29WZoKQBWXKy+XyRhPOUphMwF/GVGJ7hB0Cd7aDSy2vaqC8m0L6AeqktptCf8SqKmOpPl8BsMx0YQdOVSOy2jKyhbeFtuc52+VxvXJQydYwtR+4TSfY=
  - secure: MW4O4/CfA3BBsGXAU5UMdY7H6w4dXHKP5ksmDnxSyyQ+idTsKbWx2jpu5deY5Yqto3wsJH2BQSQMYOFHdED0Cs+32BkEdC8tkVJK+DgTKl3VvItlCCwh2JzcmnsAytAHo78jp6idHuvRaN3INKFOAB9J/fDwa7XxHaQGp7S9akE=
install:
- wget -O - $MAVEN_URL | sudo tar xvz -C /usr/local
- sudo rm /usr/local/maven
- sudo ln -s /usr/local/apache-maven-3.0.5 /usr/local/maven
before_deploy:
- mvn -Dmaven.test.skip=true package
- tar cvfz buddycloud-media-server.tgz README.md postgres target/buddycloud-media-server-*-jar-with-dependencies.jar
- shasum -a 256 buddycloud-media-server.tgz  > file.hashes
deploy:
- provider: bintray
  file: ".travis/bintray.json"
  user: "$BINTRAY_USER"
  key: "$BINTRAY_API_KEY"
  skip_cleanup: true
  on:
    branch: master
- provider: releases
  skip_cleanup: true
  api_key: GITHUB OAUTH TOKEN... to add later
  file:
  - README.md
  - target
  - manual
  - postgres
  on:
    tags: true
    branch: master
