language: java
jdk:
  - oraclejdk7
  - openjdk6
  - openjdk7
env: 
  global: 
    - MAVEN_URL=http://apache.mirrors.pair.com/maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.tar.gz 
    - secure: OPka1kcKQuWnfZHzPe8bUxOHF4fPI69J9h4bPy95Omg/IrFrvGHPuhpNWRvz2GbGTu9hcN8s2POlBoFAKBk2DFJtNLgORJrll1c/N1+OWEBmfnpaxyp5V8JmcxqISJDwPA4MD5Os+ezzMN2/VXsTaImqnHd43nY4+3K8L1o4WD8=
    - secure: N2eLGAMFSWFHgba6i9AW7agX6sIn/fWeF6ELWceTSwUi8ZN18tQqtUgcOGnlLJZPI5mHrqyAMSynxVh81ITaaSHdqRYLMyXnq2yGEG6UC9Ptw3OPf8DgyuDG9bbvMHsEtatJPy7iA1Ltn5KpZmVOkHy+1+BEoOG2G0TyaHpJJXE=
install:
  - wget -O - $MAVEN_URL | sudo tar xvz -C /usr/local 
  - sudo rm /usr/local/maven
  - sudo ln -s /usr/local/apache-maven-3.0.5 /usr/local/maven
deploy:
  provider: bintray
  file: ".travis/bintray.json"
  user: "$BINTRAY_USER"
  key: "$BINTRAY_API_KEY"
